Project: /meridian/_project.yaml
Book: /meridian/_book.yaml

<style>
devsite-code .tfo-notebook-code-cell-output {
  max-height: 300px;
  overflow: auto;
  background: rgba(255, 247, 237, 1);  /* orange bg to distinguish from input code cells */
}

devsite-code .tfo-notebook-code-cell-output + .devsite-code-buttons-container button {
  background: rgba(255, 247, 237, .7);  /* orange bg to distinguish from input code cells */
}

devsite-code[dark-code] .tfo-notebook-code-cell-output {
  background: rgba(64, 78, 103, 1);  /* medium slate */
}

devsite-code[dark-code] .tfo-notebook-code-cell-output + .devsite-code-buttons-container button {
  background: rgba(64, 78, 103, .7);  /* medium slate */
}

/* override default table styles for notebook buttons */
.devsite-table-wrapper .tfo-notebook-buttons {
  display: inline-block;
  margin-left: 3px;
  width: auto;
}

.tfo-notebook-buttons tr {
  background: 0;
  border: 0;
}

.tfo-notebook-buttons td {
  padding-left: 0;
  padding-right: 20px;
}

.tfo-notebook-buttons {
  --tfo-notebook-buttons-box-shadow: 0 1px 2px 0 rgba(60, 64, 67, .3), 0 1px 3px 1px rgba(60, 64, 67, .15);
}

.tfo-notebook-buttons a,
.tfo-notebook-buttons :link,
.tfo-notebook-buttons :visited {
  border-radius: 8px;
  box-shadow: var(--tfo-notebook-buttons-box-shadow);
  color: #202124;
  padding: 12px 24px;
  transition: box-shadow 0.2s;
}

.tfo-notebook-buttons a:hover,
.tfo-notebook-buttons a:focus {
  box-shadow: var(--tfo-notebook-buttons-box-shadow);
}

.tfo-notebook-buttons td > a {
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}

.tfo-notebook-buttons td > a > img {
  margin-right: 8px;
}
</style>

<table class="tfo-notebook-buttons tfo-api nocontent" align="left">
  <tbody>
    <tr>
      <td>
        <a target="_blank" href="https://colab.research.google.com/github/google/meridian/blob/main/demo/Meridian_Getting_Started.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
      </td>
      <td>
        <a target="_blank" href="https://github.com/google/meridian/blob/main/demo/Meridian_Getting_Started.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
      </td>
    </tr>
  </tbody>
</table>

# **Introduction to Meridian Demo**

Welcome to the Meridian end-to-end demo. This simplified demo showcases the fundamental functionalities and basic usage of the library, including working examples of the major modeling steps:


<ol start="0">
  <li><a href="#install">Install and Enviroment Configuration</a></li>
  <li><a href="#load-data">Load the data</a></li>
  <li><a href="#configure-model">Configure the model</a></li>
  <li><a href="#quality-checks">Run post-modeling quality checks</a></li>
  <li><a href="#model-diagnostics">Run model diagnostics</a></li>
  <li><a href="#generate-summary">Generate model results & two-page output</a></li>
  <li><a href="#generate-optimize">Run budget optimization & two-page output</a></li>
  <li><a href="#save-model">Save the model object</a></li>
  <li><a href="#scenario-planning">Interactive Scenario Planning</a></li>
</ol>


Note that this notebook skips all of the exploratory data analysis and preprocessing steps. It assumes that you have completed these tasks before reaching this point in the demo.

This notebook utilizes sample data. As a result, the numbers and results obtained might not accurately reflect what you encounter when working with a real dataset.

<a name="install"></a>
## Step 0: Install and Enviroment Configuration

1\. Make sure you are using one of the available GPU Colab runtimes which is **required** to run Meridian. You can change your notebook's runtime in `Runtime > Change runtime type` in the menu. All users can use the T4 GPU runtime which is sufficient to run the demo colab, free of charge. Users who have purchased one of Colab's paid plans have access to premium GPUs (such as V100, A100 or L4 Nvidia GPU).

2\. Install the latest version of Meridian, and verify that GPU is available.

In [1]:
# Install meridian: from PyPI @ latest release
!pip install --upgrade google-meridian[colab,and-cuda,schema]

# Install meridian: from PyPI @ specific version
# !pip install google-meridian[colab,and-cuda,schema]==1.3.1

# Install meridian: from GitHub @HEAD
# !pip install --upgrade "google-meridian[colab,and-cuda,schema] @ git+https://github.com/google/meridian.git@main"

Collecting google-meridian[and-cuda,colab,schema]
  Downloading google_meridian-1.5.3-py3-none-any.whl.metadata (10 kB)
Collecting arviz<0.20.0 (from google-meridian[and-cuda,colab,schema])
  Downloading arviz-0.19.0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: altair>=5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (5.5.0)
Collecting bidict (from google-meridian[and-cuda,colab,schema])
  Downloading bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: immutabledict in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (4.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (1.5.3)
Collecting natsort<8,>=7.1.1 (from google-meridian[and-cuda,colab,schema])
  Downloading natsort-7.1.1-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy<2.4.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.0.2)
Requirement already satisfied: pandas<3,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.2.2)
Requirement already satisfied: scipy<2,>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (1.16.3)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (0.14.6)
Requirement already satisfied: tensorflow<2.21,>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.19.0)
Collecting tfp-nightly==0.26.0.dev20260130 (from google-meridian[and-cuda,colab,schema])
  Downloading tfp_nightly-0.26.0.dev20260130-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tf-keras<2.21,>=2.18 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.19.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2025.12.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (5.9.5)
Collecting python-calamine (from google-meridian[and-cuda,colab,schema])
  Downloading python_calamine-0.6.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Collecting mmm-proto-schema>=1.1.2 (from google-meridian[and-cuda,colab,schema])
  Downloading mmm_proto_schema-1.1.3-py3-none-any.whl.metadata (1.7 kB)
Collecting semver (from google-meridian[and-cuda,colab,schema])
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (1.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (1.17.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (4.4.2)
Requirement already satisfied: cloudpickle>=1.3 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (3.1.2)
Requirement already satisfied: gast>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (0.7.0)
Requirement already satisfied: dm-tree in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (0.1.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (2.19.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (26.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (4.15.0)
Requirement already satisfied: setuptools>=60.0.0 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (75.2.0)
Requirement already satisfied: matplotlib>=3.5 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (3.10.0)
Requirement already satisfied: h5netcdf>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (1.8.1)
Requirement already satisfied: xarray-einstats>=0.3 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (0.10.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.1.2->google-meridian[and-cuda,colab,schema]) (1.74.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.1.2->google-meridian[and-cuda,colab,schema]) (5.29.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,colab,schema]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,colab,schema]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,colab,schema]) (2026.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.5->google-meridian[and-cuda,colab,schema]) (1.0.2)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (25.12.19)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.32.4)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (1.80.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.5.4)
Collecting nvidia-cublas-cu12==12.5.3.2 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cublas_cu12-12.5.3.2-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.5.82 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cuda_cupti_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cuda-nvcc-cu12==12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.5.82)
Collecting nvidia-cuda-nvrtc-cu12==12.5.82 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cuda_nvrtc_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.5.82 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cuda_runtime_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12==9.3.0.75 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cudnn_cu12-9.3.0.75-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12==11.2.3.61 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cufft_cu12-11.2.3.61-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.6.82 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_curand_cu12-10.3.6.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.3.83 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cusolver_cu12-11.6.3.83-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.1.3 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_cusparse_cu12-12.5.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.23.4 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.5.82 (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema])
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.46.3)
Requirement already satisfied: attrs>=18.2.0 in /usr/local/lib/python3.12/dist-packages (from dm-tree->tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (0.30.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.19.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.5->arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.1.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair>=5->google-meridian[and-cuda,colab,schema]) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.1.2)
Downloading tfp_nightly-0.26.0.dev20260130-py2.py3-none-any.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 46.3 MB/s eta 0:00:00
Downloading arviz-0.19.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 83.0 MB/s eta 0:00:00
Downloading mmm_proto_schema-1.1.3-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 8.0 MB/s eta 0:00:00
Downloading natsort-7.1.1-py3-none-any.whl (35 kB)
Downloading nvidia_cublas_cu12-12.5.3.2-py3-none-manylinux2014_x86_64.whl (363.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.3/363.3 MB 3.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 78.3 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 69.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (895 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 895.7/895.7 kB 53.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.3.0.75-py3-none-manylinux2014_x86_64.whl (577.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.2/577.2 MB 2.4 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.3.61-py3-none-manylinux2014_x86_64.whl (192.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.5/192.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.6.82-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 36.3 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.3.83-py3-none-manylinux2014_x86_64.whl (130.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.3/130.3 MB 17.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.5.1.3-py3-none-manylinux2014_x86_64.whl (217.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.6/217.6 MB 4.1 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (199.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.0/199.0 MB 6.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 76.7 MB/s eta 0:00:00
Downloading bidict-0.23.1-py3-none-any.whl (32 kB)
Downloading google_meridian-1.5.3-py3-none-any.whl (466 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.3/466.3 kB 28.9 MB/s eta 0:00:00
Downloading python_calamine-0.6.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (935 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 935.1/935.1 kB 48.7 MB/s eta 0:00:00
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Installing collected packages: semver, python-calamine, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, natsort, bidict, tfp-nightly, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, mmm-proto-schema, arviz, google-meridian
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.8.93
    Uninstalling nvidia-nvjitlink-cu12-12.8.93:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.8.93
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.5
    Uninstalling nvidia-nccl-cu12-2.27.5:
      Successfully uninstalled nvidia-nccl-cu12-2.27.5
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.90
    Uninstalling nvidia-curand-cu12-10.3.9.90:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93

In [27]:
import IPython
from meridian import constants
from meridian.analysis import analyzer
from meridian.analysis import optimizer
from meridian.analysis import summarizer
from meridian.analysis import visualizer
from meridian.analysis.review import reviewer
from meridian.data import data_frame_input_data_builder
from meridian.model import model
from meridian.model import prior_distribution
from meridian.model import spec
from meridian.schema.serde import meridian_serde
import numpy as np
import pandas as pd
from statsmodels.tsa.stattools import grangercausalitytests
from itertools import permutations
# check if GPU is available
from psutil import virtual_memory
import tensorflow as tf
import tensorflow_probability as tfp

ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))
print(
    'Num GPUs Available: ',
    len(tf.config.experimental.list_physical_devices('GPU')),
)
print(
    'Num CPUs Available: ',
    len(tf.config.experimental.list_physical_devices('CPU')),
)

Your runtime has 54.8 gigabytes of available RAM

Num GPUs Available:  1
Num CPUs Available:  1

3\. Mount a storage. Use `meridian_root` to refer the mounted root. The mounted root will be used to <a href="#save-model">save trained model</a>, <a href="#generate-summary">stage two-pager output</a> and <a href="#scenario-planning">generate scenario planning dashboard</a>.

For Colab Free/Pro user, we will use the `MyDrive` folder in Google Drive as the external storage. For Colab Enterprise user, we will use <a href="https://docs.cloud.google.com/storage/docs/cloud-storage-fuse/overview">Cloud FUSE</a> to mount a GCS bucket.

In [3]:
# @markdown If you are using Colab Free, Colab Pro, run this cell to mount your Google Drive.
from google.colab import drive
drive_mount = '/content/drive'
drive.mount(drive_mount, force_remount=True)
subfolder = '' # @param {"type":"string","placeholder": "Optional, specifying a subfolder is recommended for organizing distinct execution runs."}
# Change this "MyDrive" to other share folders name if you would like to use a different drive.
meridian_root = f'{drive_mount}/MyDrive/{subfolder}'
is_enterprise_user=False

Mounted at /content/drive

In [ ]:
# @markdown If you are using Colab Enterprise, uncomment and run this cell to mount a GCS bucket.
# import os

# project_id = ""# @param {"type":"string","placeholder": "Cloud project id"}
# bucket_name = "" # @param {"type":"string","placeholder": "GCS bucket that contains your model"}
# subfolder = "" # @param {"type":"string","placeholder": "Optional, specifying a subfolder is recommended for organizing distinct execution runs."}
# os.environ['GOOGLE_CLOUD_PROJECT'] = project_id
# !gcloud config set project {project_id}
# !gcloud auth login
# !mkdir /content/{bucket_name}

# # Uncomment below if you don't have gcsfuse installed
# #!echo "deb https://packages.cloud.google.com/apt gcsfuse-`lsb_release -c -s` main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
# #!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
# #!apt-get update
# #!apt-get install gcsfuse

# !gcsfuse --implicit-dirs {bucket_name} /content/{bucket_name}
# meridian_root = f'/content/{bucket_name}/{subfolder}'
# is_enterprise_user=True
#!fusermount -u /content/{bucket_name}

<a name="load-data"></a>
## Step 1: Load the data

Load the [simulated dataset in CSV format](https://github.com/google/meridian/blob/main/meridian/data/simulated_data/csv/geo_all_channels.csv) as follows.

1\. Read the data into a Pandas DataFrame.

In [7]:
data = pd.read_csv(
  "https://raw.githubusercontent.com/pstat197/BlueAlpha3-Synergy-Analysis/refs/heads/meridian_modeling/data/global_ads_performance_dataset.csv"
)

In [35]:
# Pivot data to create channel spend and impressions as predictors
data_pivoted = data.pivot_table(
    index='date',
    columns='platform',
    values=['ad_spend', 'impressions'],
    aggfunc='sum'
)

data_pivoted.index = pd.to_datetime(data_pivoted.index)

# Conversions (target)
conversion_total = data.groupby('date')['conversions'].sum()
conversion_total.index = pd.to_datetime(conversion_total.index)

# Make data weekly
media_weekly = data_pivoted.resample('W').sum()
conversion_weekly = conversion_total.resample('W').sum()

# Flatten grouped columns
media_weekly.columns = [
    f"{metric}_{platform}" for metric, platform in media_weekly.columns
]

# Combine dataset to include conversions
df = media_weekly.join(conversion_weekly).fillna(0)

df

,ad_spend_Google Ads,ad_spend_Meta Ads,ad_spend_TikTok Ads,impressions_Google Ads,impressions_Meta Ads,impressions_TikTok Ads,conversions
date,,,,,,,
2024-01-07,64639.29,61577.27,49140.22,758474.0,2193535.0,481041.0,5067
2024-01-14,76999.52,42569.95,40498.94,831820.0,1718508.0,683136.0,4694
2024-01-21,148613.45,63382.94,95143.26,1776068.0,1731759.0,1646653.0,9300
2024-01-28,83895.53,40246.25,52790.13,1355292.0,1308657.0,976325.0,6325
2024-02-04,102147.05,35457.61,85068.52,1339853.0,971574.0,1112566.0,6822
2024-02-11,82508.17,38310.85,56261.68,948189.0,1207324.0,1309070.0,5646
2024-02-18,160242.73,80258.62,63790.80,1816963.0,1519534.0,947858.0,7751
2024-02-25,141444.16,31803.98,32960.97,1896312.0,818040.0,586119.0,6194
2024-03-03,119319.52,35878.33,55370.17,1451487.0,1064711.0,1281280.0,6549
2024-03-10,112251.37,41523.91,53295.12,1281659.0,1608682.0,667431.0,6541
2024-03-17,123676.04,37287.31,30796.55,1466525.0,1415685.0,706041.0,5839
2024-03-24,99210.53,21212.38,38785.92,1293044.0,965400.0,787698.0,4524
2024-03-31,176326.76,29715.40,23837.50,1887837.0,1326568.0,599423.0,5984
2024-04-07,119882.48,37559.08,105164.11,1322351.0,1377293.0,1970201.0,9233
2024-04-14,220895.74,23657.81,83128.58,1924037.0,672296.0,1372900.0,8411
2024-04-21,102721.69,29991.75,62866.90,1453530.0,981472.0,1013608.0,6872
2024-04-28,105600.52,37342.27,30368.88,1365962.0,1135858.0,503108.0,3635
2024-05-05,166803.25,34449.48,38974.34,1552701.0,1124600.0,525720.0,5585
2024-05-12,82713.15,53670.47,38317.71,924876.0,1258884.0,705144.0,5039
2024-05-19,176520.22,15401.61,31959.13,1799104.0,745461.0,680668.0,6021
2024-05-26,131088.63,53907.14,43833.93,1491195.0,2062333.0,837478.0,6612
2024-06-02,129016.39,7870.85,26677.40,1318887.0,353069.0,569506.0,4433
2024-06-09,91081.06,71256.48,49822.29,1079604.0,2125660.0,1045269.0,6735
2024-06-16,67743.56,18545.41,38135.40,925065.0,586922.0,779367.0,3784
2024-06-23,106606.63,77666.41,58287.65,1452910.0,1914202.0,892001.0,7041
2024-06-30,279050.65,40845.50,14988.37,2917284.0,1458928.0,357967.0,9333
2024-07-07,57626.79,24650.58,60941.48,687583.0,848956.0,1001092.0,4182
2024-07-14,107958.13,43834.18,29929.25,1100939.0,1181127.0,775802.0,5048
2024-07-21,119354.56,31316.14,68274.69,1357113.0,759163.0,948020.0,6645
2024-07-28,163190.21,30458.15,14364.65,1785136.0,1227912.0,320837.0,4980
2024-08-04,131836.58,38259.68,25701.93,1556300.0,919734.0,482734.0,4703
2024-08-11,45165.85,28907.83,35518.18,477485.0,797838.0,682769.0,4450
2024-08-18,112925.85,65480.77,35058.72,1437301.0,2135804.0,949679.0,6393
2024-08-25,98681.60,31994.01,56693.83,1304515.0,991912.0,971151.0,6319
2024-09-01,107401.87,48872.13,51002.53,1502158.0,1616992.0,983010.0,7278
2024-09-08,195003.20,47543.69,36078.21,2244091.0,1213682.0,565095.0,6636
2024-09-15,148785.00,64235.48,48598.46,2157070.0,1463669.0,776100.0,8063
2024-09-22,76983.25,16864.61,54483.38,941819.0,729264.0,1258177.0,5341
2024-09-29,121735.04,52077.44,85508.20,1060050.0,1495423.0,1406874.0,7549
2024-10-06,50736.28,8118.66,47975.03,580168.0,424143.0,802271.0,4039
2024-10-13,53796.58,51863.97,26084.56,1056766.0,1964322.0,500244.0,5070
2024-10-20,65381.61,39371.29,66747.02,911582.0,1119853.0,1089288.0,4618
2024-10-27,167639.08,59205.78,60368.23,1849624.0,1368271.0,883865.0,8258
2024-11-03,156211.30,26975.91,109787.27,1441003.0,840778.0,1682310.0,8721
2024-11-10,129689.82,49235.67,24009.03,1691025.0,1617827.0,411030.0,6392
2024-11-17,106349.95,46963.93,90375.89,1135829.0,1307689.0,1177577.0,6764
2024-11-24,82456.54,25238.09,25207.16,1114839.0,536725.0,585636.0,3836
2024-12-01,153503.35,48457.95,25057.65,1800580.0,980251.0,530988.0,5995
2024-12-08,114739.02,40674.53,72343.94,1210608.0,1244631.0,1261074.0,7131
2024-12-15,177879.11,50531.52,96098.10,2114992.0,1502660.0,1509327.0,9369
2024-12-22,127905.81,32273.32,51550.77,1345931.0,947301.0,962246.0,6291
2024-12-29,174163.94,32666.76,35326.43,2048610.0,1233522.0,971878.0,7126
2025-01-05,31170.50,8600.54,20069.45,257004.0,287090.0,522938.0,1645

In [47]:
df = pd.read_csv(
  "https://raw.githubusercontent.com/pstat197/BlueAlpha3-Synergy-Analysis/refs/heads/meridian_modeling/data/monthly_mocha.csv"
)
df = df.loc[:, (df != 0).any()]

In [48]:
# Prepare for Granger

# Keep only spend columns (remove impressions)
spend_cols = [c for c in df.columns if "_spend" in c]

# Create dataset for Granger (exclude target)
df_gc = df[spend_cols].copy()

# Difference data to make it stationary
df_gc_diff = df_gc.diff().dropna()

print("Columns used for Granger:", spend_cols)

Columns used for Granger: ['meta_spend', 'google_spend', 'snapchat_spend', 'tiktok_spend', 'moloco_spend', 'liveintent_spend', 'beehiiv_spend', 'amazon_spend']

In [49]:
print("Spend cols:", spend_cols)
print("Shape original:", df.shape)
print("Shape differenced:", df_gc_diff.shape)

Spend cols: ['meta_spend', 'google_spend', 'snapchat_spend', 'tiktok_spend', 'moloco_spend', 'liveintent_spend', 'beehiiv_spend', 'amazon_spend']
Shape original: (74, 18)
Shape differenced: (73, 8)

In [50]:
gc_results = {}

channels = df_gc_diff.columns

# Run Granger causality tests
for x1, x2 in permutations(channels, 2):
    test_result = grangercausalitytests(
        df_gc_diff[[x1, x2]],
        maxlag=3,
        verbose=False
    )

    p_values = {
        lag: test_result[lag][0]['ssr_ftest'][1]
        for lag in range(1, 4)
    }

    gc_results[(x1, x2)] = p_values

# Convert to wide DataFrame
gc_df = pd.DataFrame(gc_results).T
gc_df.columns = [f"lag_{i}_pvalue" for i in range(1, 4)]

print("\nRaw Granger Results:")
print(gc_df.head())

# -----------------------------
# CREATE long_df (key step)
# -----------------------------
long_df = (
    gc_df.reset_index()
    .rename(columns={"level_0": "target", "level_1": "driver"})
    .melt(
        id_vars=["target", "driver"],
        var_name="lag",
        value_name="p_value"
    )
)

# Extract numeric lag
long_df["lag"] = long_df["lag"].str.extract(r"lag_(\d+)_pvalue").astype(int)

# -----------------------------
# MULTIPLE TESTING CORRECTIONS
# -----------------------------
m = len(long_df)

# Bonferroni
long_df["bonferroni_p"] = np.minimum(long_df["p_value"] * m, 1.0)
long_df["sig_bonf_05"] = long_df["bonferroni_p"] < 0.05

# Benjamini-Hochberg (FDR)
def fdr_bh(pvals):
    pvals = np.asarray(pvals, dtype=float)
    order = np.argsort(pvals)
    ranked = pvals[order]

    q = ranked * len(pvals) / (np.arange(1, len(pvals) + 1))
    q = np.minimum.accumulate(q[::-1])[::-1]
    q = np.clip(q, 0, 1)

    out = np.empty_like(q)
    out[order] = q
    return out

long_df["fdr_q"] = fdr_bh(long_df["p_value"].values)
long_df["sig_fdr_05"] = long_df["fdr_q"] < 0.05

# -----------------------------
# SELECT SIGNIFICANT RESULTS
# -----------------------------
significant = long_df[long_df["sig_fdr_05"]]

best_lags = (
    significant.sort_values(["target", "driver", "p_value"])
    .groupby(["target", "driver"], as_index=False)
    .first()
)

# -----------------------------
# OUTPUTS
# -----------------------------
print("\n==============================")
print("SIGNIFICANT DRIVERS (FDR):")
print(best_lags["driver"].unique().tolist())

print("\n==============================")
print("TOP RELATIONSHIPS:")
print(
    best_lags.sort_values("fdr_q").head(15)[
        ["target", "driver", "lag", "p_value", "fdr_q"]
    ]
)

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(

Raw Granger Results:
                             lag_1_pvalue  lag_2_pvalue  lag_3_pvalue
meta_spend google_spend          0.373219      0.844775      0.867218
           snapchat_spend        0.556460      0.853165      0.942809
           tiktok_spend          0.075610      0.110496      0.212783
           moloco_spend          0.138498      0.479829      0.583483
           liveintent_spend      0.297042      0.342096      0.542898

==============================
SIGNIFICANT DRIVERS (FDR):
['meta_spend', 'liveintent_spend']

==============================
TOP RELATIONSHIPS:
         target            driver  lag       p_value     fdr_q
0  amazon_spend        meta_spend    3  8.202508e-09  0.000001
1  google_spend  liveintent_spend    3  5.795737e-04  0.024342

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/stattools.py:1556: FutureWarning: verbose is deprecated since functions should not print results
  warnings.warn(

In [59]:
# -----------------------------
# Select top N relationships
# -----------------------------
top_n = 3

significant = long_df[long_df["sig_fdr_05"]]

top_relationships = (
    significant
    .sort_values("fdr_q")
    .groupby(["target", "driver"], as_index=False)
    .first()
    .sort_values("fdr_q")
    .head(top_n)
)

# -----------------------------
# Create interaction features (LEVELS ONLY)
# -----------------------------
df_with_interactions = df.copy()

for _, row in top_relationships.iterrows():
    target = row["target"]
    driver = row["driver"]

    col_name = f"{driver}_x_{target}"

    df_with_interactions[col_name] = (
        df_with_interactions[driver] * df_with_interactions[target]
    )

# -----------------------------
# Merge interactions back
# -----------------------------
interaction_cols = [c for c in df_with_interactions.columns if "_x_" in c]

df_final = df.merge(
    df_with_interactions[interaction_cols],
    left_index=True,
    right_index=True,
    how="left"
).fillna(0)

# -----------------------------
# Outputs
# -----------------------------
print("\nTop relationships used for interactions:")
print(top_relationships[["target", "driver", "lag", "p_value", "fdr_q"]])

print("\nFinal dataset shape:", df_final.shape)

df_final.head()

Top relationships used for interactions:
         target            driver  lag       p_value     fdr_q
0  amazon_spend        meta_spend    3  8.202508e-09  0.000001
1  google_spend  liveintent_spend    3  5.795737e-04  0.024342

Final dataset shape: (74, 20)

,date,subscriptions,meta_spend,meta_impressions,google_spend,google_impressions,snapchat_spend,snapchat_impressions,tiktok_spend,tiktok_impressions,moloco_spend,moloco_impressions,liveintent_spend,liveintent_impressions,beehiiv_spend,beehiiv_impressions,amazon_spend,amazon_impressions,meta_spend_x_amazon_spend,liveintent_spend_x_google_spend
0,8/4/25,15540,91538.06648,16572258,116667.9945,6473132,94750.04035,3420454,0.0,0,6564.524233,367206,37766.44904,371854,18190.10332,181901,0.0,0,0.0,4.406136e+09
1,7/28/25,14525,93840.18612,25300600,180486.9558,9487127,99447.23218,3235285,0.0,0,18111.083980,820589,38543.27888,347850,20063.91811,200639,0.0,0,0.0,6.956559e+09
2,7/21/25,16880,48403.06780,14099214,200817.3250,7909118,84738.57435,4766750,0.0,0,9714.794608,369806,39697.42202,322865,20828.00074,208280,0.0,0,0.0,7.971930e+09
3,7/14/25,20113,49470.96783,13652072,215770.9242,7789279,83204.40500,4022680,0.0,0,16831.841440,554980,40561.34006,570418,24097.34426,240973,0.0,0,0.0,8.751958e+09
4,7/7/25,16492,48948.28744,10121002,209231.9668,6806878,82642.37271,4532105,0.0,0,17624.908800,894891,40012.42040,483619,19967.60420,199676,0.0,0,0.0,8.371877e+09

In [60]:
import pandas as pd

# -----------------------------
# Step 1: Build lagged features (main effects)
# -----------------------------
df_lagged = df.copy()

for col in spend_cols:
    for lag in range(1, 3):
        df_lagged[f"{col}_lag{lag}"] = df_lagged[col].shift(lag)

df_lagged = df_lagged.dropna()

# -----------------------------
# Step 2: Attach interaction features (already built earlier)
# -----------------------------
interaction_cols = [c for c in df_final.columns if "_x_" in c]

df_mmm = df_lagged.join(df_final[interaction_cols], how="left")

# -----------------------------
# Step 3: Clean alignment issues
# -----------------------------
df_mmm = df_mmm.dropna().reset_index(drop=True)

# -----------------------------
# Output
# -----------------------------
print(df_mmm.head())
print("\nFinal MMM dataset shape:", df_mmm.shape)

      date  subscriptions   meta_spend  meta_impressions  google_spend  \
0  7/21/25          16880  48403.06780          14099214   200817.3250
1  7/14/25          20113  49470.96783          13652072   215770.9242
2   7/7/25          16492  48948.28744          10121002   209231.9668
3  6/30/25          15459  47241.55544           8953395   197595.7996
4  6/23/25          15798      0.00000                 0   203264.8346

   google_impressions  snapchat_spend  snapchat_impressions  tiktok_spend  \
0             7909118     84738.57435               4766750           0.0
1             7789279     83204.40500               4022680           0.0
2             6806878     82642.37271               4532105           0.0
3            11115242     87738.66067               3995130           0.0
4             9827238     90905.70724               4935027           0.0

   tiktok_impressions  ...  moloco_spend_lag1  moloco_spend_lag2  \
0                   0  ...       18111.083980        6564.524233
1                   0  ...        9714.794608       18111.083980
2                   0  ...       16831.841440        9714.794608
3                   0  ...       17624.908800       16831.841440
4                   0  ...       10830.161140       17624.908800

   liveintent_spend_lag1  liveintent_spend_lag2  beehiiv_spend_lag1  \
0            38543.27888            37766.44904         20063.91811
1            39697.42202            38543.27888         20828.00074
2            40561.34006            39697.42202         24097.34426
3            40012.42040            40561.34006         19967.60420
4            35024.21339            40012.42040         15891.76053

   beehiiv_spend_lag2  amazon_spend_lag1  amazon_spend_lag2  \
0         18190.10332                0.0                0.0
1         20063.91811                0.0                0.0
2         20828.00074                0.0                0.0
3         24097.34426                0.0                0.0
4         19967.60420                0.0                0.0

   meta_spend_x_amazon_spend  liveintent_spend_x_google_spend
0                        0.0                     7.971930e+09
1                        0.0                     8.751958e+09
2                        0.0                     8.371877e+09
3                        0.0                     6.920637e+09
4                        0.0                     4.547180e+09

[5 rows x 36 columns]

Final MMM dataset shape: (72, 36)

In [ ]:
# Meridian REQUIRES these columns

# Time must be string format YYYY-MM-DD
df_lagged["time"] = pd.date_range(
    start="2020-01-01",
    periods=len(df_lagged),
    freq="D"
).astype(str)

# Required placeholders
df_lagged["revenue_per_conversion"] = 1.0
df_lagged["population"] = 1.0

print(df_lagged[["time"]].head())

In [ ]:
# Get all spend columns
media_spend_cols = [c for c in df_lagged.columns if "_spend" in c]

# Build matching impression columns
media_cols = []
final_spend_cols = []
channels = []

for spend_col in media_spend_cols:
    base = spend_col.replace("_spend", "")
    impression_col = f"{base}_impressions"

    # Only keep if BOTH exist
    if impression_col in df_lagged.columns:
        final_spend_cols.append(spend_col)
        media_cols.append(impression_col)
        channels.append(base)

# Overwrite with filtered lists
media_spend_cols = final_spend_cols

print("Channels used:", channels)
print("Spend cols:", media_spend_cols)
print("Impression cols:", media_cols)

In [ ]:
builder = data_frame_input_data_builder.DataFrameInputDataBuilder(
    kpi_type="non_revenue",
    default_kpi_column="subscriptions",
    default_revenue_per_kpi_column="revenue_per_conversion",
)

builder = (
    builder.with_kpi(df_lagged)
    .with_revenue_per_kpi(df_lagged)
    .with_population(df_lagged)
    .with_media(
        df_lagged,
        media_cols=media_cols,
        media_spend_cols=media_spend_cols,
        media_channels=channels
    )
)

# IMPORTANT: don't call this "data"
mmm_data = builder.build()

print(type(mmm_data))

In [ ]:
# Initialize Model
prior = spec.prior_distribution.PriorDistribution(
    roi_m=tfp.distributions.LogNormal(
        loc=0.2,
        scale=0.9,
        name=constants.ROI_M
    )
)

model_spec = spec.ModelSpec(
    prior=prior,
    enable_aks=True
)

mmm = model.Meridian(
    input_data=mmm_data,
    model_spec=model_spec
)

print("Model ready")

In [ ]:
# Bayesian sampling (this is where learning happens)

mmm.sample_posterior(
    n_chains=1,
    n_adapt=500,
    n_burnin=500,
    n_keep=500
)

print("Sampling complete")

In [ ]:
analyzer_obj = analyzer.Analyzer(mmm)

# Extract key outputs
roi = analyzer_obj.roi()
mroi = analyzer_obj.marginal_roi()
inc = analyzer_obj.incremental_outcome()

print("ROI:\n", roi)
print("\nMarginal ROI:\n", mroi)
print("\nIncremental Outcome:\n", inc)

In [ ]:
import numpy as np
import pandas as pd

analyzer_obj = analyzer.Analyzer(mmm)

roi = analyzer_obj.roi().numpy()
mroi = analyzer_obj.marginal_roi().numpy()
inc = analyzer_obj.incremental_outcome().numpy()

roi = np.squeeze(roi)
mroi = np.squeeze(mroi)
inc = np.squeeze(inc)

roi_mean = roi.mean(axis=0)
roi_p5 = np.percentile(roi, 5, axis=0)
roi_p95 = np.percentile(roi, 95, axis=0)

mroi_mean = mroi.mean(axis=0)
mroi_p5 = np.percentile(mroi, 5, axis=0)
mroi_p95 = np.percentile(mroi, 95, axis=0)

inc_mean = inc.mean(axis=0)

results = pd.DataFrame({
    "ROI_mean": roi_mean,
    "ROI_p5": roi_p5,
    "ROI_p95": roi_p95,
    "Marginal_ROI_mean": mroi_mean,
    "Incremental_mean": inc_mean
})

print(results)

In [ ]:
health_summary = reviewer.ModelReviewer(mmm).run()

filename = 'health_card.html'
health_summary.output_model_health_card(filename=filename, filepath=meridian_root)
IPython.display.HTML(filename=f'{meridian_root}{filename}')

<a name="model-diagnostics"></a>
## Step 4: Run model diagnostics

To further assess convergence and model fit, you can use the methods from `visualizer` module.

1\. Assess convergence. Run the following code to generate r-hat statistics. R-hat close to 1.0 indicate convergence. R-hat < 1.2 indicates approximate convergence and is a reasonable threshold for many problems.

In [ ]:
model_diagnostics = visualizer.ModelDiagnostics(mmm)
model_diagnostics.plot_rhat_boxplot()

2\. Assess the model's fit by comparing the expected sales against the actual sales.

In [ ]:
model_fit = visualizer.ModelFit(mmm)
model_fit.plot_model_fit()

For more information and additional model diagnostics checks, see [Modeling diagnostics](https://developers.google.com/meridian/docs/user-guide/model-diagnostics).

<a name="generate-summary"></a>
## Step 5: Generate model results & two-page output

To export the two-page HTML summary output, initialize the `Summarizer` class with the model object. Then pass in the filename, filepath, start date, and end date to `output_model_results_summary` to run the summary for that time duration and save it to the specified file.

In [ ]:
mmm_summarizer = summarizer.Summarizer(mmm)

In [ ]:
filepath = meridian_root
start_date = '2020-01-01'
end_date = '2024-01-15'
mmm_summarizer.output_model_results_summary(
    'summary_output.html', filepath, start_date, end_date
)

Here is a preview of the two-page output based on the simulated data:

In [ ]:
IPython.display.HTML(filename=f'{meridian_root}/summary_output.html')

For a customized two-page report, model results summary table, and individual visualizations, see [Model results report](https://developers.google.com/meridian/docs/user-guide/generate-model-results-report) and [plot media visualizations](https://developers.google.com/meridian/docs/user-guide/plot-media-visualizations).

<a name="generate-optimize"></a>
## Step 6: Run budget optimization & generate an optimization report

You can choose what scenario to run for the budget allocation. In default scenario, you find the optimal allocation across channels for a given budget to maximize the return on investment (ROI).

Alternatively, if you would like to have a sharable interactive dashboard, check out [Meridian Scenario Planner](https://developers.google.com/meridian/docs/scenario-planning/meridian-scenario-planner).

1\. Instantiate the `BudgetOptimizer` class and run the `optimize()` method without any customization, to run the default library's Fixed Budget Scenario to maximize ROI.

In [ ]:
%%time
budget_optimizer = optimizer.BudgetOptimizer(mmm)
optimization_results = budget_optimizer.optimize()

2\. Export the 2-page HTML optimization report, which contains optimized spend allocations and ROI.

In [ ]:
filepath = meridian_root
optimization_results.output_optimization_summary(
    'optimization_output.html', filepath
)

In [ ]:
IPython.display.HTML(filename=f'{meridian_root}/optimization_output.html')

For information about customized optimization scenarios, such as flexible budget scenarios, see [Budget optimization scenarios](https://developers.google.com/meridian/docs/user-guide/budget-optimization-scenarios). For more information about optimization results summary and individual visualizations, see [optimization results output](https://developers.google.com/meridian/docs/user-guide/generate-optimization-results-output) and [optimization visualizations](https://developers.google.com/meridian/docs/user-guide/plot-optimization-visualizations).


Optimization can also be performed on a hypothetical data representing a future scenario. The new data takes the same structure as the input data and encodes an anticipated flighting pattern, cost per media unit, and revenue per kpi.

3\. Load the [simulated dataset in CSV format](https://github.com/google/meridian/blob/main/meridian/data/simulated_data/csv/hypothetical_geo_all_channels.csv) into Pandas DataFrame.

In [ ]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/google/meridian/refs/heads/main/meridian/data/simulated_data/csv/hypothetical_geo_all_channels.csv"
)


4\. New data is read from a csv file and converted into a set of multi-dimensional arrays. The arrays are used to construct a `DataTensors` instance, which is passed to `optimize()` as the `new_data` argument.

Constructing a `DataTensors` instance requires that all arrays have "time" and "geo" dimensions. Alternatively, the `BudgetOptimizer.create_optimization_tensors` method can be used to construct a `DataTensors` instance. This helper method can simplify the process, particularly when you do not need "time" and "geo" dimensions for all inputs. For example, it can be convenient if you want to assume a constant "revenue per kpi" or "cost per media unit" for all geos and time periods.

In [ ]:
n_geos = mmm.n_geos
n_media_channels = mmm.n_media_channels
n_non_media_channels = mmm.n_non_media_channels
n_organic_media_channels = mmm.n_organic_media_channels

# The number of time periods and time range do not need to match the input data.
df[constants.TIME] = pd.to_datetime(df[constants.TIME], errors='coerce')
unique_times = sorted(df[constants.TIME].unique())
n_times = len(unique_times)

geos = mmm.input_data.geo.values
media_channels = mmm.input_data.media_channel.values
media_cols = [f"{channel}_impression" for channel in media_channels]
media_spend_cols = [f"{channel}_spend" for channel in media_channels]
non_media_treatment_cols = ['Promo']
organic_media_cols = ['Organic_channel0_impression']
organic_media_channels = ['Organic_channel0']
revenue_per_kpi_col='revenue_per_conversion'
times_str = [time.strftime(constants.DATE_FORMAT) for time in unique_times]

media_np = np.zeros((n_geos, n_times, n_media_channels))
media_spend_np = np.zeros((n_geos, n_times, n_media_channels))
non_media_treatment_np = np.zeros((n_geos, n_times, n_non_media_channels))
organic_media_np = np.zeros((n_geos, n_times, n_organic_media_channels))
revenue_per_kpi_np = np.zeros((n_geos, n_times))

df_grouped = df.set_index([constants.GEO, constants.TIME])
for geo_idx, geo in enumerate(geos):
  for time_idx, time in enumerate(unique_times):
    row = df_grouped.loc[(geo, time)]
    media_np[geo_idx, time_idx, :] = row[media_cols].values
    media_spend_np[geo_idx, time_idx, :] = row[media_spend_cols].values
    non_media_treatment_np[geo_idx, time_idx, :] = row[non_media_treatment_cols].values
    organic_media_np[geo_idx, time_idx, :] = row[organic_media_cols].values
    revenue_per_kpi_np[geo_idx, time_idx] = row[revenue_per_kpi_col].item()

data_tensors = analyzer.DataTensors(
    media=tf.convert_to_tensor(media_np, dtype=tf.float32),
    media_spend=tf.convert_to_tensor(media_spend_np, dtype=tf.float32),
    non_media_treatments=tf.convert_to_tensor(non_media_treatment_np, dtype=tf.float32),
    organic_media=tf.convert_to_tensor(organic_media_np, dtype=tf.float32),
    revenue_per_kpi=tf.convert_to_tensor(revenue_per_kpi_np, dtype=tf.float32),
    time=tf.convert_to_tensor(times_str, dtype=tf.string),
)
# Default values for `budget` and `pct_of_spend` are derived from the `new_data`,
# but these values can be overridden without modifying the `new_data` itself.
hypothetical_optimization_results = budget_optimizer.optimize(
    new_data=data_tensors,
    budget=50_000_000,
    pct_of_spend=[.2, .1, .2, .2, .3]
)

5\. Export the 2-page HTML optimization report.

In [ ]:
filepath = meridian_root
hypothetical_optimization_results.output_optimization_summary(
    'hypothetical_optimization_output.html', filepath
)

In [ ]:
IPython.display.HTML(filename=f'{meridian_root}/hypothetical_optimization_output.html')

<a name="save-model"></a>
## Step 7: Save the model object

We recommend that you save the model object for future use. This helps you to  avoid repetitive model runs and saves time and computational resources. After the model object is saved, you can load it at a later stage to continue the analysis or visualizations without having to re-run the model.

Run the following codes to save the model object:

In [ ]:
file_path = f'{meridian_root}/saved_mmm.binpb'
meridian_serde.save_meridian(mmm, file_path)
print(f'model is saved at {file_path}')

Run the following codes to load the saved model:

In [ ]:
mmm = meridian_serde.load_meridian(file_path)

In [ ]:
# @markdown If a GCS bucket is mounted, run this cell to unmount it.
!fusermount -u /content/{bucket_name}

<a name="scenario-planning"></a>
## Step 8: Interactive Scenario Planning
[Meridian Scenario Planner](https://developers.google.com/meridian/docs/scenario-planning/meridian-scenario-planner) is a tool that allow advertisers to create a sharable and interactive dashboard from Colab; you can reuse the saved model from this Colab for dashboard generation.